### ISSUE TITLE
[FEAT.] Implementing pointers.

### ISSUE THREAD

**Issue by EralpCelebi** [Soda-Programming-Language/sodac#1]
Implementation of basic pointers for `sodac`
 
### To-Do 

- [ ] Implement Syntax
    - [ ]  Add lexer rules for `ref`, `deref` and `addr`.

- [ ] Implement Tree
    - [ ] Modify `TypeAST` node to support pointers.
    - [ ] Add `ref`, `deref`, `addr` expression nodes.

- [ ] Implement Grammer
    - [ ] Add grammer for aformentioned nodes.
    - [ ] Modify `type :` grammer to support pointers

- [ ] Implement Util
    - [ ] Modify `CastTo` to support pointers #2 

- [ ] Implement Docs
    - [ ] Add usage to wiki.
    - [ ] Add details to wiki.

### Expectations
* Ability to create pointers,
* Ability to derefrence, and refrence every `expr`,
* Ability to create refrences from adresses,
* Ability to create integers from refrences,
