### ISSUE TITLE
[FEAT.] Implement explicit casting.

### ISSUE THREAD

**Issue by EralpCelebi** [Soda-Programming-Language/sodac#2]
- description -
 
### To-Do 

- [ ] Implement Syntax
    - [ ] Add `to` keyword.

- [ ] Implement Tree
    - [ ] Add a `CastNode`

- [ ] Implement Grammer
    - [ ] Add grammer for `CastNode`

- [ ] Implement Util
    - [ ] Add `void` type and support for `ptr void`
    - [ ] Add support for bitcasting to `CastTo`

- [ ] Implement Docs
   - [ ] Add usage information,
   - [ ] Add detailed information,
