### ISSUE TITLE
[FEAT.] Implement a build system.

### ISSUE THREAD

**Issue by EralpCelebi** [Soda-Programming-Language/sodac#5]
Implement a build system for creating executables for host-platforms 
### To-Do 
- [ ] Implement Util
    - [ ] Create a utility to automate the builds.
    - [ ] Create a utility to download `clang` releases automatically.

- [ ] Implement Docs
    - [ ] Add usage documentation.
    - [ ] Add detailed information.

### Expectations
* Ability to build a standalone executable without requiring shared objects.
* Ability to setup a compilation environment automatically,
