### ISSUE TITLE
[FEAT.] Implement arrays.

### ISSUE THREAD

**Issue by EralpCelebi** [Soda-Programming-Language/sodac#8]
Description goes here,
 
### To-Do 

- [x] Implement Syntax
   - [x] Implement `of`  keyword.
- [ ] Implement Grammar
    - [ ] Implement `<count> of <type>` grammar rule.
- [ ] Implement Tree
   - [ ] Implement array expression.
   - [ ] Implement array indexing.
   - [ ] Modify types to support arrays.
- [ ] Implement Utility
    - [ ] Implement casting to arrays.
- [ ] Implement Docs
    - [ ] Add usage documentation.
    - [ ] Add detailed information.

### Expectations
* Expecting this to happen
* Expecting that to happen
